manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: denis-koshenkov
      url-base: https://github.com/denis-koshenkov

  projects:
    - name: nrf
      remote: nrfconnect
      repo-path: sdk-nrf
      revision: v3.0.2
      import:
        path-prefix: nrf-sdk
    - name: cpputest
      remote: denis-koshenkov
      revision: 7710d1a37719150aac97110df954f40527002080 # v4.0 + test assert plugin

  self:
    west-commands: scripts/west-commands.yml
