manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: denis-koshenkov
      url-base: https://github.com/denis-koshenkov

  projects:
    - name: nrf
      remote: nrfconnect
      repo-path: sdk-nrf
      revision: v3.2.0
      import:
        path-prefix: nrf-sdk
    - name: cpputest
      remote: denis-koshenkov
      revision: 8df1f5a4827c0749e3556c99f8c3c24809327bcf # v4.0 + test assert plugin
    - name: sensirion-sht3x
      remote: denis-koshenkov
      revision: v3.0.0

  self:
    west-commands: scripts/west-commands.yml
