manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: cpputest
      url-base: https://github.com/cpputest

  projects:
    - name: nrf
      remote: nrfconnect
      repo-path: sdk-nrf
      revision: v3.0.2
      import:
        path-prefix: nrf-sdk
    - name: cpputest
      remote: cpputest
      revision: v4.0
