manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: denis-koshenkov
      url-base: https://github.com/denis-koshenkov

  projects:
    - name: nrf
      remote: nrfconnect
      repo-path: sdk-nrf
      revision: v3.0.2
      import:
        path-prefix: nrf-sdk
    - name: cpputest
      remote: denis-koshenkov
      revision: 90f3383b20c0db7666d6cfeff25367accf129889 # v4.0 + test assert plugin

  self:
    west-commands: scripts/west-commands.yml
