#ifndef ENV_ALERT_SYSTEM_SRC_INTERFACES_DEFS_INCLUDE_HAL_LIGHT_INTENSITY_SENSOR_H
#define ENV_ALERT_SYSTEM_SRC_INTERFACES_DEFS_INCLUDE_HAL_LIGHT_INTENSITY_SENSOR_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "light_intensity.h"

/**
 * @brief Callback type definition to execute when a new light intensity sample becomes available.
 *
 * @param sample Value of the generated light intensity sample.
 * @param user_data User data.
 */
typedef void (*LightIntensitySensorNewSampleCb)(LightIntensity sample, void *user_data);

/**
 * @brief LightIntensity sensor HAL interface definition.
 */
typedef struct LightIntensitySensor {
    /**
     * @brief Register a callback to execute whenever a new light intensity sample is generated by the sensor.
     *
     * @param cb Callback to register.
     * @param user_data User data to pass to the callback when invoked.
     */
    void (*register_new_sample_cb)(LightIntensitySensorNewSampleCb cb, void *user_data);

    /**
     * @brief Start the generation of light intensity samples.
     *
     * If new sample callback is registered, it will start being invoked whenever a new sample becomes generated.
     */
    void (*start)();
} LightIntensitySensor;

#ifdef __cplusplus
}
#endif

#endif /* ENV_ALERT_SYSTEM_SRC_INTERFACES_DEFS_INCLUDE_HAL_LIGHT_INTENSITY_SENSOR_H */
