#ifndef ENV_ALERT_SYSTEM_SRC_APP_PORT_INTERFACES_HAL_TEMPERATURE_SENSOR_H
#define ENV_ALERT_SYSTEM_SRC_APP_PORT_INTERFACES_HAL_TEMPERATURE_SENSOR_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "temperature.h"

/**
 * @brief Callback type definition to execute when a new temperature sample becomes available.
 *
 * @param sample Value of the generated temperature sample.
 * @param user_data User data.
 */
typedef void (*TemperatureSensorNewSampleCb)(Temperature sample, void *user_data);

/**
 * @brief Temperature sensor HAL interface definition.
 */
typedef struct TemperatureSensor {
    /**
     * @brief Register a callback to execute whenever a new temperature sample is generated by the sensor.
     *
     * @param cb Callback to register.
     * @param user_data User data to pass to the callback when invoked.
     */
    void (*register_new_sample_cb)(TemperatureSensorNewSampleCb cb, void *user_data);

    /**
     * @brief Start the generation of temperature samples.
     *
     * If new sample callback is registered, it will start being invoked whenever a new sample becomes generated.
     *
     * This function must only be called once. If this function is called for the second time, an assert is raised.
     */
    void (*start)();
} TemperatureSensor;

#ifdef __cplusplus
}
#endif

#endif /* ENV_ALERT_SYSTEM_SRC_APP_PORT_INTERFACES_HAL_TEMPERATURE_SENSOR_H */
