#ifndef ENV_ALERT_SYSTEM_SRC_HAL_DEF_PRESSURE_SENSOR_H
#define ENV_ALERT_SYSTEM_SRC_HAL_DEF_PRESSURE_SENSOR_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "pressure.h"

/**
 * @brief Callback type definition to execute when a new pressure sample becomes available.
 *
 * @param sample Value of the generated pressure sample.
 * @param user_data User data.
 */
typedef void (*PressureSensorNewSampleCb)(Pressure sample, void *user_data);

/**
 * @brief Pressure sensor HAL interface definition.
 */
typedef struct PressureSensor {
    /**
     * @brief Register a callback to execute whenever a new pressure sample is generated by the sensor.
     *
     * @param cb Callback to register.
     * @param user_data User data to pass to the callback when invoked.
     */
    void (*register_new_sample_cb)(PressureSensorNewSampleCb cb, void *user_data);

    /**
     * @brief Start the generation of pressure samples.
     *
     * If new sample callback is registered, it will start being invoked whenever a new sample becomes generated.
     */
    void (*start)();
} PressureSensor;

#ifdef __cplusplus
}
#endif

#endif /* ENV_ALERT_SYSTEM_SRC_HAL_DEF_PRESSURE_SENSOR_H */
