#include "CppUTest/CommandLineTestRunner.h"
#include "CppUTest/TestHarness_c.h"

TEST_GROUP_C_WRAPPER(TemperatureRequirement)
{
    TEST_GROUP_C_TEARDOWN_WRAPPER(TemperatureRequirement);
};

TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorGEQValueGreater);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsFalseOperatorGEQValueLess);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorGEQValueEqual);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorLEQValueLess);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorLEQValueEqual);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsFalseOperatorLEQValueGreater);
