#include "CppUTest/CommandLineTestRunner.h"
#include "CppUTest/TestHarness_c.h"

TEST_GROUP_C_WRAPPER(TemperatureRequirement)
{
    TEST_GROUP_C_TEARDOWN_WRAPPER(TemperatureRequirement);
};

TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorGEQValueGreater);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsFalseOperatorGEQValueLess);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorGEQValueEqual);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorLEQValueLess);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorLEQValueEqual);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsFalseOperatorLEQValueGreater);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorGEQBothValuesEqualZero);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorLEQBothValuesEqualZero);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorGEQValueGreaterBothNegative);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsFalseOperatorGEQValueLessBothNegative);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorGEQValueGreaterOneNegative);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsFalseOperatorLEQValueGreaterBothNegative);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsTrueOperatorLEQValueLessBothNegative);
TEST_C_WRAPPER(TemperatureRequirement, evaluateReturnsFalseOperatorLEQValueGreaterOneNegative);
TEST_C_WRAPPER(TemperatureRequirement, getAlertIdReturnsAlertId1PassedToCreate);
TEST_C_WRAPPER(TemperatureRequirement, getAlertIdReturnsAlertId2PassedToCreate);
