#ifndef ENV_ALERT_SYSTEM_SRC_PORT_UNIT_TEST_OFF_TARGET_INTERFACES_HEADER_EAS_LOG_H
#define ENV_ALERT_SYSTEM_SRC_PORT_UNIT_TEST_OFF_TARGET_INTERFACES_HEADER_EAS_LOG_H

/* Logs are not needed in unit test port */
#define EAS_LOG_ENABLE_IN_FILE()
#define EAS_LOG_INF(...)

#endif /* ENV_ALERT_SYSTEM_SRC_PORT_UNIT_TEST_OFF_TARGET_INTERFACES_HEADER_EAS_LOG_H */
