#ifndef ENV_ALERT_SYSTEM_SRC_INTERFACES_IMPLEMENTATIONS_EAS_LOG_DISABLED_EAS_LOG_H
#define ENV_ALERT_SYSTEM_SRC_INTERFACES_IMPLEMENTATIONS_EAS_LOG_DISABLED_EAS_LOG_H

/* Empty macros that do nothing */
#define EAS_LOG_ENABLE_IN_FILE()
#define EAS_LOG_INF(...)

#endif /* ENV_ALERT_SYSTEM_SRC_INTERFACES_IMPLEMENTATIONS_EAS_LOG_DISABLED_EAS_LOG_H */
