#ifndef ENV_ALERT_SYSTEM_SRC_PORT_NRF52840DK_INCLUDE_EAS_ASSERT_H
#define ENV_ALERT_SYSTEM_SRC_PORT_NRF52840DK_INCLUDE_EAS_ASSERT_H

#include <zephyr/sys/__assert.h>

#define EAS_ASSERT(expr) __ASSERT_NO_MSG(expr)

#endif /* ENV_ALERT_SYSTEM_SRC_PORT_NRF52840DK_INCLUDE_EAS_ASSERT_H */
