#ifndef ENV_ALERT_SYSTEM_SRC_PORT_PROD_FW_INCLUDE_EAS_ASSERT_H
#define ENV_ALERT_SYSTEM_SRC_PORT_PROD_FW_INCLUDE_EAS_ASSERT_H

#include <zephyr/sys/__assert.h>

#define EAS_ASSERT(expr) __ASSERT_NO_MSG(expr)

#endif /* ENV_ALERT_SYSTEM_SRC_PORT_PROD_FW_INCLUDE_EAS_ASSERT_H */
