#ifndef ENV_ALERT_SYSTEM_SRC_APP_GLUE_EVENT_HANDLERS_NEW_SAMPLE_HANDLER_H
#define ENV_ALERT_SYSTEM_SRC_APP_GLUE_EVENT_HANDLERS_NEW_SAMPLE_HANDLER_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "temperature.h"
#include "pressure.h"
#include "humidity.h"
#include "light_intensity.h"

/**
 * @brief Event handlers that handle new sample events.
 *
 * These events are pushed to the central event queue whenever a new sensor sample is generated by the HAL.
 */

/**
 * @brief Handles a "new temperature sample" event.
 *
 * @param temperature Sample value.
 */
void new_sample_handler_temperature(Temperature temperature);

/**
 * @brief Handles a "new pressure sample" event.
 *
 * @param pressure Sample value.
 */
void new_sample_handler_pressure(Pressure pressure);

/**
 * @brief Handles a "new humidity" sample event.
 *
 * @param humidity Sample value.
 */
void new_sample_handler_humidity(Humidity humidity);

/**
 * @brief Handles a "new light intensity" sample event.
 *
 * @param light_intensity Sample value.
 */
void new_sample_handler_light_intensity(LightIntensity light_intensity);

#ifdef __cplusplus
}
#endif

#endif /* ENV_ALERT_SYSTEM_SRC_APP_GLUE_EVENT_HANDLERS_NEW_SAMPLE_HANDLER_H */
