#ifndef ENV_ALERT_SYSTEM_SRC_APP_PORT_INTERFACES_HAL_HUMIDITY_SENSOR_H
#define ENV_ALERT_SYSTEM_SRC_APP_PORT_INTERFACES_HAL_HUMIDITY_SENSOR_H

#include "humidity.h"

/**
 * @brief Callback type definition to execute when a new humidity sample becomes available.
 *
 * @param sample Value of the generated humidity sample.
 * @param user_data User data.
 */
typedef void (*HumiditySensorNewSampleCb)(Humidity sample, void *user_data);

/**
 * @brief Humidity sensor HAL interface definition.
 */
typedef struct {
    /**
     * @brief Register a callback to execute whenever a new humidity sample is generated by the sensor.
     *
     * @param cb Callback to register.
     * @param user_data User data to pass to the callback when invoked.
     */
    void (*register_new_sample_cb)(HumiditySensorNewSampleCb cb, void *user_data);

    /**
     * @brief Start the generation of humidity samples.
     *
     * If new sample callback is registered, it will start being invoked whenever a new sample becomes generated.
     *
     * This function must only be called once. If this function is called for the second time, an assert is raised.
     */
    void (*start)();
} HumiditySensor;

#endif /* ENV_ALERT_SYSTEM_SRC_APP_PORT_INTERFACES_HAL_HUMIDITY_SENSOR_H */
